# Goal - To deploy the built images from CI steps one the CI workflow is succeded

name: CD

on:
  workflow-run:
    workflows: ['CI']
    types: [completed]
    branches:
      - advanced

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: copy example.env to main .env
        run: cp .env.example .env

      # install docker and docker compose on the self hosted reunner manually befor  doing loggin below
      # sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
      # sudo usermod -aG docker $USER
      # newgrp docker

      - name: docker setup (login)
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: deploy the containers with docker compose
        run: |
          docker compose pull
          docker compose up -d
